defaults: &defaults
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 5
  username: root
  password: 8JNWU1wj

development:
  database: one_development
  socket: /tmp/mysql.sock
  <<: *defaults

test: &test
  database: one_test
  socket: /tmp/mysql.sock
  <<: *defaults

production:
  host: localhost
  database: one_production
  <<: *defaults
